### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by takeshi-chance17** [takeshi-chance17/protospace-33826#5]
ProtoSpaceのURL
https://protospace-33826.herokuapp.com/

**Comment by kubota-tec** [comment]
@takeshi-chance17 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

**その他**
`他のユーザーが投稿したプロトタイプの編集ページにURLを直接入力して遷移しようとすると、トップページにリダイレクトされる`
→こちら現在他のユーザーの投稿も編集可能な状態です。ご確認お願いいたします。


修正が完了しましたら、再度protospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。

**Comment by takeshi-chance17** [comment]
修正しました。

**Comment by iwataayumu** [comment]
@takeshi-chance17 さん、ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
